// src/components/SpeciesDistributionPlots.tsx
import React from 'react';
import { createROCPlot, createDistributionMap, createVariableImportancePlot, createFuturePredictionsPlot } from '~/lib/visualization/species_distribution_plots';
import type { SamplingPoint } from '~/lib/data/synthetic_valparaiso_data';
import type { ModelResults } from '~/lib/models/species_distribution_models';

interface SpeciesDistributionPlotsProps {
  data: SamplingPoint[];
  results: ModelResults;
  speciesName: string;
}

export const SpeciesDistributionPlots: React.FC<SpeciesDistributionPlotsProps> = ({ 
  data, 
  results, 
  speciesName 
}) => {
  // Verificar que todos los datos necesarios estén presentes
  if (!data || !results || !results.predictions || !results.observed || !results.evaluation) {
    return <div>Error: Datos incompletos para generar las visualizaciones</div>;
  }

  return (
    <div className="space-y-8">
      <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
        {/* Model Evaluation */}
        <div className="bg-[#152238] rounded-lg p-6">
          <h3 className="text-lg font-semibold mb-4 text-white">Evaluación del Modelo</h3>
          <div className="space-y-4">
            <div className="grid grid-cols-2 gap-4">
              <div>
                <p className="text-sm text-gray-400">AUC</p>
                <p className="text-xl font-bold text-white">
                  {results.evaluation?.auc?.toFixed(3) ?? 'N/A'}
                </p>
              </div>
              <div>
                <p className="text-sm text-gray-400">Boyce</p>
                <p className="text-xl font-bold text-white">
                  {results.evaluation?.boyce?.toFixed(3) ?? 'N/A'}
                </p>
              </div>
              <div>
                <p className="text-sm text-gray-400">Precisión</p>
                <p className="text-xl font-bold text-white">
                  {results.evaluation?.accuracy?.toFixed(3) ?? 'N/A'}
                </p>
              </div>
              <div>
                <p className="text-sm text-gray-400">Sensibilidad</p>
                <p className="text-xl font-bold text-white">
                  {results.evaluation?.sensitivity?.toFixed(3) ?? 'N/A'}
                </p>
              </div>
              <div>
                <p className="text-sm text-gray-400">Especificidad</p>
                <p className="text-xl font-bold text-white">
                  {results.evaluation?.specificity?.toFixed(3) ?? 'N/A'}
                </p>
              </div>
            </div>
            <div dangerouslySetInnerHTML={{ 
              __html: createROCPlot(results.observed, results.predictions) 
            }} />
          </div>
        </div>

        {/* Distribution Map */}
        <div className="bg-[#152238] rounded-lg p-6">
          <h3 className="text-lg font-semibold mb-4 text-white">Mapa de Distribución</h3>
          <div dangerouslySetInnerHTML={{ 
            __html: createDistributionMap(data, results.predictions) 
          }} />
        </div>

        {/* Variable Importance */}
        <div className="bg-[#152238] rounded-lg p-6">
          <h3 className="text-lg font-semibold mb-4 text-white">Importancia de Variables</h3>
          <div dangerouslySetInnerHTML={{ 
            __html: createVariableImportancePlot(results.importance || {}) 
          }} />
        </div>

        {/* Future Predictions */}
        <div className="bg-[#152238] rounded-lg p-6">
          <h3 className="text-lg font-semibold mb-4 text-white">Predicciones Futuras</h3>
          <div dangerouslySetInnerHTML={{ 
            __html: createFuturePredictionsPlot(
              results.habitatPredictions?.current || [],
              results.habitatPredictions?.future || []
            ) 
          }} />
        </div>
      </div>
    </div>
  );
};

// src/components/SpeciesDistributionPlots.svelte
<script lang="ts">
  import type { SamplingPoint } from '~/lib/data/synthetic_valparaiso_data';
  import type { ModelResults } from '~/lib/models/species_distribution_models';
  import { createROCPlot, createDistributionMap, createVariableImportancePlot, createFuturePredictionsPlot } from '~/lib/visualization/species_distribution_plots';

  export let data: SamplingPoint[];
  export let results: ModelResults;
  export let speciesName: string;

  // Crear las visualizaciones
  const rocPlot = createROCPlot(results);
  const distributionMap = createDistributionMap(data, results, { title: `Distribution of ${speciesName}` });
  const importancePlot = createVariableImportancePlot(results);
  const futurePlot = createFuturePredictionsPlot(results);
</script>

<div class="plots-container">
  <div class="plot-section">
    <h2>Model Evaluation</h2>
    <div class="plot" bind:this={rocPlotContainer}>
      {@html rocPlot}
    </div>
    <div class="metrics">
      <p>AUC: {results.evaluation.auc.toFixed(3)}</p>
      <p>Boyce Index: {results.evaluation.boyce.toFixed(3)}</p>
      <p>Accuracy: {results.evaluation.accuracy.toFixed(3)}</p>
      <p>Sensitivity: {results.evaluation.sensitivity.toFixed(3)}</p>
      <p>Specificity: {results.evaluation.specificity.toFixed(3)}</p>
    </div>
  </div>

  <div class="plot-section">
    <h2>Distribution Map</h2>
    <div class="plot" bind:this={mapContainer}>
      {@html distributionMap}
    </div>
  </div>

  <div class="plot-section">
    <h2>Variable Importance</h2>
    <div class="plot" bind:this={importanceContainer}>
      {@html importancePlot}
    </div>
  </div>

  <div class="plot-section">
    <h2>Future Predictions</h2>
    <div class="plot" bind:this={futureContainer}>
      {@html futurePlot}
    </div>
  </div>
</div>

<style>
  .plots-container {
    display: grid;
    grid-template-columns: repeat(2, 1fr);
    gap: 2rem;
    padding: 1rem;
  }

  .plot-section {
    background: white;
    border-radius: 8px;
    padding: 1rem;
    box-shadow: 0 2px 4px rgba(0,0,0,0.1);
  }

  .plot {
    width: 100%;
    height: 400px;
    margin: 1rem 0;
    border: 1px solid #ddd;
    border-radius: 4px;
    overflow: hidden;
  }

  .metrics {
    display: grid;
    grid-template-columns: repeat(2, 1fr);
    gap: 1rem;
    margin-top: 1rem;
  }

  .metrics p {
    margin: 0;
    padding: 0.5rem;
    background: #f5f5f5;
    border-radius: 4px;
  }

  h2 {
    margin: 0 0 1rem 0;
    color: #333;
    font-size: 1.2rem;
  }
</style>
